#!/bin/sh

# PROVIDE: emmett
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="emmett"
rcvar="emmett_enable"


load_rc_config $name
: ${emmett_enable:=no}

command="/www/venv/bin/${name}"
command_args="-a /www/src/app.py serve"
pidfile="/var/run/${name}.pid"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
restart_cmd="${name}_stop && ${name}_start"

emmett_start()
{
        daemon -p ${pidfile} ${command} ${command_args}
        echo "Emmett started"
}

emmett_stop() {
    if [ -e ${pidfile} ];then
        kill `cat ${pidfile}`
        rm ${pidfile}
        echo "Emmett stopped"
    fi
}

emmett_restart(){
    echo "Emmett restarting"
    emmett_stop
    emmett_start
}

load_rc_config $name
run_rc_command "$1"